import type { EffectDefinition } from './abilities';
import type { CareerCategoryTag } from './careers';
import type { DeckId } from './decks';

export interface CardDefinition {
  id: string;
  deck: DeckId;
  title: string;
  description: string;
  effect: string;
  value: string;
  rarity: 'STANDARD' | 'RARE';
  target?: 'SELF' | 'ALL_PLAYERS' | 'ALL_OTHER_PLAYERS';
  careerTags?: readonly CareerCategoryTag[];
  effects: readonly EffectDefinition[];
}

export const cards: readonly CardDefinition[] = [
  {
    id: 'wealth-seed-capital',
    deck: 'wealth',
    title: 'Seed Capital',
    description: 'A small opening becomes money you can actually deploy.',
    effect: 'Gain Wealth.',
    value: '+$15K',
    rarity: 'STANDARD',
    effects: [{ type: 'ADD_WEALTH', amount: 15000, reason: 'Seed Capital' }],
  },
  {
    id: 'wealth-corporate-deal',
    deck: 'wealth',
    title: 'Corporate Deal',
    description: 'The business crowd closes ranks and gets paid.',
    effect: 'BUSINESS careers gain Wealth.',
    value: 'BUSINESS +$20K',
    rarity: 'RARE',
    target: 'ALL_PLAYERS',
    careerTags: ['business'],
    effects: [{ type: 'ADD_WEALTH', target: 'ALL_PLAYERS', careerTag: 'business', amount: 20000, reason: 'Corporate Deal' }],
  },
  {
    id: 'wealth-hustle-season',
    deck: 'wealth',
    title: 'Hustle Season',
    description: 'The longest shifts finally start paying back.',
    effect: 'SERVICE and HUSTLE careers gain Wealth.',
    value: 'SERVICE/HUSTLE +$10K',
    rarity: 'STANDARD',
    target: 'ALL_PLAYERS',
    careerTags: ['service', 'hustle'],
    effects: [{ type: 'ADD_WEALTH', target: 'ALL_PLAYERS', careerTags: ['service', 'hustle'], amount: 10000, reason: 'Hustle Season' }],
  },
  {
    id: 'wealth-rent-spike',
    deck: 'wealth',
    title: 'Rent Spike',
    description: 'Your timing is perfect. Everyone else pays for it.',
    effect: 'You gain Wealth. Other players lose a little Wealth.',
    value: '+$10K / Others -$5K',
    rarity: 'RARE',
    target: 'ALL_OTHER_PLAYERS',
    effects: [
      { type: 'ADD_WEALTH', amount: 10000, reason: 'Rent Spike' },
      { type: 'REMOVE_WEALTH', target: 'ALL_OTHER_PLAYERS', amount: 5000, reason: 'Rent Spike' },
    ],
  },
  {
    id: 'ai-pattern-found',
    deck: 'ai',
    title: 'Pattern Found',
    description: 'The noise resolves into a clean edge.',
    effect: 'Gain AI Skill.',
    value: '+2 AI',
    rarity: 'STANDARD',
    effects: [{ type: 'ADD_AI_SKILL', amount: 2, reason: 'Pattern Found' }],
  },
  {
    id: 'ai-ai-boom',
    deck: 'ai',
    title: 'AI Boom',
    description: 'Digital workers ride the next wave first.',
    effect: 'DIGITAL careers gain AI Skill.',
    value: 'DIGITAL +3 AI',
    rarity: 'RARE',
    target: 'ALL_PLAYERS',
    careerTags: ['digital'],
    effects: [{ type: 'ADD_AI_SKILL', target: 'ALL_PLAYERS', careerTag: 'digital', amount: 3, reason: 'AI Boom' }],
  },
  {
    id: 'ai-biohack',
    deck: 'ai',
    title: 'Biohack',
    description: 'Lab coats and white papers both find a sharper signal.',
    effect: 'MEDICAL and SCIENCE careers gain AI Skill.',
    value: 'MEDICAL/SCIENCE +1 AI',
    rarity: 'STANDARD',
    target: 'ALL_PLAYERS',
    careerTags: ['medical', 'science'],
    effects: [{ type: 'ADD_AI_SKILL', target: 'ALL_PLAYERS', careerTags: ['medical', 'science'], amount: 1, reason: 'Biohack' }],
  },
  {
    id: 'ai-open-source-sprint',
    deck: 'ai',
    title: 'Open Source Sprint',
    description: 'The repo moves fast, and so do you.',
    effect: 'Gain AI Skill and Influence.',
    value: '+1 AI / +2 INFL.',
    rarity: 'STANDARD',
    effects: [
      { type: 'ADD_AI_SKILL', amount: 1, reason: 'Open Source Sprint' },
      { type: 'ADD_INFLUENCE', amount: 2, reason: 'Open Source Sprint' },
    ],
  },
  {
    id: 'fame-viral-moment',
    deck: 'fame',
    title: 'Viral Moment',
    description: 'Creative careers catch the signal and run with it.',
    effect: 'CREATIVE careers gain Fame.',
    value: 'CREATIVE +4 FAME',
    rarity: 'RARE',
    target: 'ALL_PLAYERS',
    careerTags: ['creative'],
    effects: [{ type: 'ADD_FAME', target: 'ALL_PLAYERS', careerTag: 'creative', amount: 4, reason: 'Viral Moment' }],
  },
  {
    id: 'fame-click-farm',
    deck: 'fame',
    title: 'Click Farm',
    description: 'Attention spikes for you while everyone else loses control of the story.',
    effect: 'Gain Fame. Other players lose Influence.',
    value: '+3 FAME / Others -1 INFL.',
    rarity: 'STANDARD',
    target: 'ALL_OTHER_PLAYERS',
    effects: [
      { type: 'ADD_FAME', amount: 3, reason: 'Click Farm' },
      { type: 'REMOVE_INFLUENCE', target: 'ALL_OTHER_PLAYERS', amount: 1, reason: 'Click Farm' },
    ],
  },
  {
    id: 'fame-backstage-pass',
    deck: 'fame',
    title: 'Backstage Pass',
    description: 'The room opens up before the lights do.',
    effect: 'Gain Fame and Influence.',
    value: '+2 FAME / +2 INFL.',
    rarity: 'STANDARD',
    effects: [
      { type: 'ADD_FAME', amount: 2, reason: 'Backstage Pass' },
      { type: 'ADD_INFLUENCE', amount: 2, reason: 'Backstage Pass' },
    ],
  },
  {
    id: 'fame-headline-cycle',
    deck: 'fame',
    title: 'Headline Cycle',
    description: 'The crowd only wants whoever is already moving fast.',
    effect: 'PERFORMANCE careers gain Fame.',
    value: 'PERFORMANCE +3 FAME',
    rarity: 'STANDARD',
    target: 'ALL_PLAYERS',
    careerTags: ['performance'],
    effects: [{ type: 'ADD_FAME', target: 'ALL_PLAYERS', careerTag: 'performance', amount: 3, reason: 'Headline Cycle' }],
  },
  {
    id: 'lifestyle-full-reset',
    deck: 'lifestyle',
    title: 'Full Reset',
    description: 'You step back just long enough to feel human again.',
    effect: 'Gain Lifestyle.',
    value: '+4 LIFE',
    rarity: 'STANDARD',
    effects: [{ type: 'ADD_LIFESTYLE', amount: 4, reason: 'Full Reset' }],
  },
  {
    id: 'lifestyle-pit-crew',
    deck: 'lifestyle',
    title: 'Pit Crew Upgrade',
    description: 'Performance careers find a better rhythm immediately.',
    effect: 'PERFORMANCE careers gain Lifestyle.',
    value: 'PERFORMANCE +2 LIFE',
    rarity: 'STANDARD',
    target: 'ALL_PLAYERS',
    careerTags: ['performance'],
    effects: [{ type: 'ADD_LIFESTYLE', target: 'ALL_PLAYERS', careerTag: 'performance', amount: 2, reason: 'Pit Crew Upgrade' }],
  },
  {
    id: 'lifestyle-wellness-stipend',
    deck: 'lifestyle',
    title: 'Wellness Stipend',
    description: 'Service careers finally get something back from the grind.',
    effect: 'SERVICE careers gain Lifestyle.',
    value: 'SERVICE +3 LIFE',
    rarity: 'RARE',
    target: 'ALL_PLAYERS',
    careerTags: ['service'],
    effects: [{ type: 'ADD_LIFESTYLE', target: 'ALL_PLAYERS', careerTag: 'service', amount: 3, reason: 'Wellness Stipend' }],
  },
  {
    id: 'lifestyle-luxury-burn',
    deck: 'lifestyle',
    title: 'Luxury Burn',
    description: 'It costs more than it should, but you still walk out glowing.',
    effect: 'Lose a little Wealth to gain a lot of Lifestyle.',
    value: '-$5K / +5 LIFE',
    rarity: 'STANDARD',
    effects: [
      { type: 'REMOVE_WEALTH', amount: 5000, reason: 'Luxury Burn' },
      { type: 'ADD_LIFESTYLE', amount: 5, reason: 'Luxury Burn' },
    ],
  },
  {
    id: 'influence-warm-introduction',
    deck: 'influence',
    title: 'Warm Introduction',
    description: 'Someone opens the right door before you knock.',
    effect: 'Gain Influence.',
    value: '+3 INFL.',
    rarity: 'STANDARD',
    effects: [{ type: 'ADD_INFLUENCE', amount: 3, reason: 'Warm Introduction' }],
  },
  {
    id: 'influence-legal-victory',
    deck: 'influence',
    title: 'Legal Victory',
    description: 'The legal class wins the argument and the room.',
    effect: 'LEGAL careers gain Influence.',
    value: 'LEGAL +4 INFL.',
    rarity: 'RARE',
    target: 'ALL_PLAYERS',
    careerTags: ['legal'],
    effects: [{ type: 'ADD_INFLUENCE', target: 'ALL_PLAYERS', careerTag: 'legal', amount: 4, reason: 'Legal Victory' }],
  },
  {
    id: 'influence-boardroom-whisper',
    deck: 'influence',
    title: 'Boardroom Whisper',
    description: 'Business players get the call before the market does.',
    effect: 'BUSINESS careers gain Influence and Wealth.',
    value: 'BUSINESS +2 INFL. / +$10K',
    rarity: 'STANDARD',
    target: 'ALL_PLAYERS',
    careerTags: ['business'],
    effects: [
      { type: 'ADD_INFLUENCE', target: 'ALL_PLAYERS', careerTag: 'business', amount: 2, reason: 'Boardroom Whisper' },
      { type: 'ADD_WEALTH', target: 'ALL_PLAYERS', careerTag: 'business', amount: 10000, reason: 'Boardroom Whisper' },
    ],
  },
  {
    id: 'influence-call-in-favor',
    deck: 'influence',
    title: 'Call In A Favor',
    description: 'You collect. Everyone else suddenly owes attention.',
    effect: 'Gain Influence. Other players lose Influence.',
    value: '+2 INFL. / Others -1 INFL.',
    rarity: 'STANDARD',
    target: 'ALL_OTHER_PLAYERS',
    effects: [
      { type: 'ADD_INFLUENCE', amount: 2, reason: 'Call In A Favor' },
      { type: 'REMOVE_INFLUENCE', target: 'ALL_OTHER_PLAYERS', amount: 1, reason: 'Call In A Favor' },
    ],
  },
  {
    id: 'gamble-market-surge',
    deck: 'gamble',
    title: 'Market Surge',
    description: 'Risk careers cash in while the line is still climbing.',
    effect: 'RISK careers gain Wealth.',
    value: 'RISK +$25K',
    rarity: 'RARE',
    target: 'ALL_PLAYERS',
    careerTags: ['risk'],
    effects: [{ type: 'ADD_WEALTH', target: 'ALL_PLAYERS', careerTag: 'risk', amount: 25000, reason: 'Market Surge' }],
  },
  {
    id: 'gamble-market-crash',
    deck: 'gamble',
    title: 'Market Crash',
    description: 'Risk careers feel the floor disappear first.',
    effect: 'RISK careers lose Wealth.',
    value: 'RISK -$15K',
    rarity: 'RARE',
    target: 'ALL_PLAYERS',
    careerTags: ['risk'],
    effects: [{ type: 'REMOVE_WEALTH', target: 'ALL_PLAYERS', careerTag: 'risk', amount: 15000, reason: 'Market Crash' }],
  },
  {
    id: 'gamble-regulatory-crackdown',
    deck: 'gamble',
    title: 'Regulatory Crackdown',
    description: 'Digital careers lose a little room to move.',
    effect: 'DIGITAL careers lose Influence.',
    value: 'DIGITAL -1 INFL.',
    rarity: 'STANDARD',
    target: 'ALL_PLAYERS',
    careerTags: ['digital'],
    effects: [{ type: 'REMOVE_INFLUENCE', target: 'ALL_PLAYERS', careerTag: 'digital', amount: 1, reason: 'Regulatory Crackdown' }],
  },
  {
    id: 'gamble-lucky-break',
    deck: 'gamble',
    title: 'Lucky Break',
    description: 'The safe line pays. The risky line pays even more.',
    effect: 'Gain Wealth. RISK careers gain extra Wealth.',
    value: '+$15K / RISK +$10K',
    rarity: 'STANDARD',
    careerTags: ['risk'],
    effects: [
      { type: 'ADD_WEALTH', amount: 15000, reason: 'Lucky Break' },
      { type: 'ADD_WEALTH', careerTag: 'risk', amount: 10000, reason: 'Lucky Break' },
    ],
  },
];

export const cardsForDeck = (deck: DeckId): readonly CardDefinition[] => cards.filter((card) => card.deck === deck);
export const examplesForDeck = cardsForDeck;

export function getCard(id: string): CardDefinition | undefined {
  return cards.find((card) => card.id === id);
}

export function drawCard(deck: DeckId): CardDefinition {
  const available = cardsForDeck(deck);
  return available[Math.floor(Math.random() * available.length)] ?? available[0];
}
