import type { CareerCategoryTag } from './careers';
import type { EffectType } from './abilities';
import type { DeckId } from './decks';
import type { PlayerStat } from './player';

export type CardTarget = 'SELF' | 'RANDOM_OPPONENT' | 'WEALTH_LEADER' | 'WEALTH_TRAILER' | 'ALL_OPPONENTS';

export type CardEffect =
  | { kind: 'STAT'; stat: PlayerStat; amount: number; target?: CardTarget; careerTag?: CareerCategoryTag; reason?: string }
  | { kind: 'TRANSFER_WEALTH'; amount: number; target: 'RANDOM_OPPONENT' | 'WEALTH_LEADER' | 'WEALTH_TRAILER'; reason?: string }
  | { kind: 'MODIFY_SALARY'; amount: number; target?: CardTarget; careerTag?: CareerCategoryTag; reason?: string }
  | { kind: 'PROTECT'; amount?: number; target?: CardTarget; careerTag?: CareerCategoryTag; blockedEffectTypes?: EffectType[]; reason?: string }
  | { kind: 'REWARD_MODIFIER'; stat: PlayerStat; amount: number; target?: CardTarget; careerTag?: CareerCategoryTag; reason?: string }
  | { kind: 'RISK'; chance: number; win: readonly CardEffect[]; loss: readonly CardEffect[]; reason?: string };

export interface CardDefinition {
  id: string;
  deck: DeckId;
  title: string;
  description: string;
  effect: string;
  value: string;
  rarity: 'STANDARD' | 'RARE';
  effects: readonly CardEffect[];
  /** Unique visual concept used to create this card's art; never shown as gameplay copy. */
  artCue: string;
}

const stat = (statName: PlayerStat, amount: number, target: CardTarget = 'SELF', careerTag?: CareerCategoryTag): CardEffect => ({
  kind: 'STAT', stat: statName, amount, target, careerTag,
});
const transfer = (amount: number, target: 'RANDOM_OPPONENT' | 'WEALTH_LEADER' | 'WEALTH_TRAILER'): CardEffect => ({
  kind: 'TRANSFER_WEALTH', amount, target,
});
const salary = (amount: number, target: CardTarget = 'SELF', careerTag?: CareerCategoryTag): CardEffect => ({
  kind: 'MODIFY_SALARY', amount, target, careerTag,
});
const protect = (amount = 1, blockedEffectTypes?: EffectType[], target: CardTarget = 'SELF'): CardEffect => ({
  kind: 'PROTECT', amount, blockedEffectTypes, target,
});
const reward = (statName: PlayerStat, amount: number, target: CardTarget = 'SELF', careerTag?: CareerCategoryTag): CardEffect => ({
  kind: 'REWARD_MODIFIER', stat: statName, amount, target, careerTag,
});
const risk = (chance: number, win: readonly CardEffect[], loss: readonly CardEffect[]): CardEffect => ({
  kind: 'RISK', chance, win, loss,
});
const card = (
  id: string,
  deck: DeckId,
  title: string,
  description: string,
  effect: string,
  value: string,
  effects: readonly CardEffect[],
  artCue: string,
  rarity: CardDefinition['rarity'] = 'STANDARD',
): CardDefinition => ({ id, deck, title, description, effect, value, effects, artCue, rarity });

export const cards: readonly CardDefinition[] = [
  // WEALTH
  card('wealth-seed', 'wealth', 'Seed Capital', 'A small opening becomes a real opportunity.', 'Gain $12,500 Wealth.', '+$12,500', [stat('wealth', 12500)], 'A sealed black investment case opens to reveal a tiny gold seedling growing through scattered banknotes.'),
  card('wealth-windfall', 'wealth', 'Unexpected Return', 'An old bet finally makes its way home.', 'Gain $28,750 Wealth.', '+$28,750', [stat('wealth', 28750)], 'A dusty arcade prize machine erupts with antique coins and one absurdly oversized golden check.'),
  card('wealth-tax-refund', 'wealth', 'The Refund Window', 'A forgotten filing finally clears review.', 'Gain $6,000 Wealth.', '+$6,000', [stat('wealth', 6000)], 'A robotic tax clerk stamps a glowing refund envelope while a relieved player catches falling coins.'),
  card('wealth-audit', 'wealth', 'Audit Season', 'The paperwork finds a few expensive surprises.', 'Lose $8,000 Wealth; Business careers recover $4,000.', '-$8,000 / business +$4,000', [stat('wealth', -8000), stat('wealth', 4000, 'SELF', 'business')], 'A towering holographic audit scanner exposes red financial lines across a nervous founder’s glass office.'),
  card('wealth-angel-check', 'wealth', 'Angel Check', 'A believer funds the idea before the pitch deck loads.', 'Gain $16,000 Wealth; Entrepreneur careers gain another $9,000.', '+$16,000 / entrepreneur +$9,000', [stat('wealth', 16000), stat('wealth', 9000, 'SELF', 'entrepreneur')], 'A chrome angel investor lowers a luminous check into a chaotic startup demo room.', 'RARE'),
  card('wealth-repair-bill', 'wealth', 'The Repair Bill', 'The premium machine chooses the premium failure mode.', 'Lose $9,000 Wealth and 1 Lifestyle.', '-$9,000 / -1 LIFE', [stat('wealth', -9000), stat('lifestyle', -1)], 'A luxury electric coupe sits open on a service lift as a tiny repair invoice glows ominously.'),
  card('wealth-patent-payout', 'wealth', 'Patent Payout', 'A clever design keeps earning while you sleep.', 'Gain $12,000 Wealth; Digital careers gain 1 AI Skill.', '+$12,000 / digital +1 AI', [stat('wealth', 12000), stat('aiSkill', 1, 'SELF', 'digital')], 'A luminous circuit patent unfolds into a stream of royalties beside a precise silicon wafer.', 'RARE'),
  card('wealth-side-contract', 'wealth', 'Side Contract', 'A small gig lands a surprisingly serious client.', 'Gain $8,000 Wealth and 1 Influence; Gig careers add $2,500 to salary.', '+$8,000 / +1 INFL. / gig salary +$2,500', [stat('wealth', 8000), stat('influence', 1), salary(2500, 'SELF', 'gig')], 'A delivery rider signs a sleek contract on a phone while a city of small gigs lights up behind them.'),
  card('wealth-rent-hike', 'wealth', 'Rent Hike', 'The view is unchanged. The monthly number is not.', 'Lose $7,500 Wealth and 1 Lifestyle.', '-$7,500 / -1 LIFE', [stat('wealth', -7500), stat('lifestyle', -1)], 'A high-rise apartment window displays a rising rent notice over a tiny potted plant and empty wallet.'),
  card('wealth-insider-bid', 'wealth', 'Insider Bid', 'A quiet auction rewards the fastest read in the room.', 'Take $8,000 from the Wealth leader and gain 1 Influence.', 'Up to +$8,000 / +1 INFL.', [transfer(8000, 'WEALTH_LEADER'), stat('influence', 1)], 'Two sharply dressed bidders face off over a miniature red-lit company in a sealed auction chamber.', 'RARE'),
  card('wealth-late-fee', 'wealth', 'Late Fee Spiral', 'One missed date turns into a very modern penalty stack.', 'Lose $5,000 Wealth and gain 1 Fame from the public complaint.', '-$5,000 / +1 FAME', [stat('wealth', -5000), stat('fame', 1)], 'A comically long stack of glowing overdue envelopes tumbles from a vending machine into a camera flash.'),
  card('wealth-liquidation', 'wealth', 'Liquidation Weekend', 'The collection goes. The cash clears by Monday.', 'Gain $21,000 Wealth and lose 2 Lifestyle.', '+$21,000 / -2 LIFE', [stat('wealth', 21000), stat('lifestyle', -2)], 'A neon-lit luxury closet is rapidly emptied into a ruthless auction conveyor.'),
  card('wealth-silent-partner', 'wealth', 'Silent Partner', 'A backer wants no spotlight, just a reliable return.', 'Gain $5,000 Wealth; your next positive Wealth gain this turn gets +$5,000.', '+$5,000 / next gain +$5,000', [stat('wealth', 5000), reward('wealth', 5000)], 'A faceless partner’s gloved hand places a gold token beside an immaculate balance sheet.'),
  card('wealth-market-volatility', 'wealth', 'Volatility Spike', 'The market moves first. You find out after.', '50%: gain $22,000 Wealth. Otherwise lose $12,000.', '+$22,000 or -$12,000', [risk(0.5, [stat('wealth', 22000)], [stat('wealth', -12000)])], 'A split-screen trading floor shows a green rocket launch on one side and a red market cliff on the other.', 'RARE'),
  card('wealth-handshake', 'wealth', 'Handshake Fee', 'A polished introduction comes with an unspoken invoice.', 'Take $7,500 from a random opponent and gain 2 Influence.', 'Up to +$7,500 / +2 INFL.', [transfer(7500, 'RANDOM_OPPONENT'), stat('influence', 2)], 'A chrome handshake between rivals transfers a glowing coin through their joined palms.', 'RARE'),

  // AI SKILL
  card('ai-pattern', 'ai', 'Pattern Found', 'The noise resolves into an edge you can use.', 'Gain 3 AI Skill.', '+3 AI', [stat('aiSkill', 3)], 'A dark data storm aligns into a clean constellation of luminous machine-learning nodes.'),
  card('ai-model', 'ai', 'New Model', 'A better question leads to a better machine.', 'Gain 6 AI Skill.', '+6 AI', [stat('aiSkill', 6)], 'A compact black neural core unfolds into a precise, radiant new model above a workbench.', 'RARE'),
  card('ai-prompt-bounty', 'ai', 'Prompt Bounty', 'The client pays for the answer, not the prompt.', 'Gain 2 AI Skill and $8,000 Wealth.', '+2 AI / +$8,000', [stat('aiSkill', 2), stat('wealth', 8000)], 'A glowing prompt window catches a rare digital fish made from code and small golden coins.'),
  card('ai-agent-fleet', 'ai', 'Agent Fleet', 'Your workflow now has a workflow for the workflow.', 'Gain $12,000 Wealth; Digital careers gain 2 AI Skill.', '+$12,000 / digital +2 AI', [stat('wealth', 12000), stat('aiSkill', 2, 'SELF', 'digital')], 'A coordinated fleet of tiny service robots runs a glass office while one engineer watches the dashboard.'),
  card('ai-robot-tax', 'ai', 'Automation Dividend', 'The machines do the work. The invoice still needs a human.', 'Gain $12,000 Wealth; Digital opponents lose 1 AI Skill.', '+$12,000 / digital rivals -1 AI', [stat('wealth', 12000), stat('aiSkill', -1, 'ALL_OPPONENTS', 'digital')], 'A robot assembly line sends a dividend coin to one worker while rival terminals flicker offline.'),
  card('ai-model-collapse', 'ai', 'Model Collapse', 'The model learned from its own bad homework.', 'Lose 3 AI Skill and $5,000 Wealth.', '-3 AI / -$5,000', [stat('aiSkill', -3), stat('wealth', -5000)], 'A synthetic data loop folds in on itself, crushing a glowing server rack into a dark spiral.'),
  card('ai-algorithmic-breakthrough', 'ai', 'Algorithmic Breakthrough', 'A stubborn problem finally gives up its shape.', 'Gain 4 AI Skill; Digital careers gain 2 more.', '+4 AI / digital +2 AI', [stat('aiSkill', 4), stat('aiSkill', 2, 'SELF', 'digital')], 'A luminous algorithmic maze opens into a clear, geometric path above a midnight lab table.', 'RARE'),
  card('ai-workflow-overclock', 'ai', 'Workflow Overclock', 'You move faster before the rest of the turn catches up.', 'Gain 1 AI Skill; next positive AI gain this turn gets +2.', '+1 AI / next gain +2', [stat('aiSkill', 1), reward('aiSkill', 2)], 'A technician flips a guarded red switch as data streams accelerate through a transparent workstation.'),
  card('ai-disruption-wave', 'ai', 'Disruption Wave', 'A new tool makes yesterday’s edge look expensive.', 'Digital opponents lose 2 AI Skill; you gain 1 Influence.', 'digital rivals -2 AI / +1 INFL.', [stat('aiSkill', -2, 'ALL_OPPONENTS', 'digital'), stat('influence', 1)], 'A bright autonomous wave rolls through a city of obsolete screens and startled tech workers.', 'RARE'),
  card('ai-deepfake-leak', 'ai', 'Deepfake Leak', 'The synthetic clip is fake. The apology tour is real.', 'Lose 3 Fame; Digital careers gain 1 AI Skill.', '-3 FAME / digital +1 AI', [stat('fame', -3), stat('aiSkill', 1, 'SELF', 'digital')], 'A distorted holographic face glitches across a newsroom wall as a forensic analyst isolates pixels.'),
  card('ai-open-source-pivot', 'ai', 'Open-Source Pivot', 'The community fixes what the roadmap could not.', 'Gain 3 AI Skill and 1 Influence.', '+3 AI / +1 INFL.', [stat('aiSkill', 3), stat('influence', 1)], 'A circle of independent builders connects a glowing open-source machine from mismatched parts.'),
  card('ai-synthetic-lab', 'ai', 'Synthetic Lab', 'The prototype works. The compute bill does too.', 'Gain 4 AI Skill and lose $6,000 Wealth.', '+4 AI / -$6,000', [stat('aiSkill', 4), stat('wealth', -6000)], 'A translucent synthetic organism grows inside a glass server chamber beside a draining power meter.'),
  card('ai-human-override', 'ai', 'Human Override', 'A person checks the output before the system makes it everyone’s problem.', 'Gain 2 Influence and block the next AI Skill penalty.', '+2 INFL. / block 1 AI penalty', [stat('influence', 2), protect(1, ['REMOVE_AI_SKILL'])], 'A human hand reaches through a grid of cold machine arms to press a bright manual override.'),
  card('ai-licensing-deal', 'ai', 'Licensing Deal', 'The demo was free. The deployment agreement was not.', 'Gain $16,000 Wealth; Digital careers gain 1 AI Skill.', '+$16,000 / digital +1 AI', [stat('wealth', 16000), stat('aiSkill', 1, 'SELF', 'digital')], 'A sleek licensing contract hovers above a chip etched with a tiny, unmistakable crown.', 'RARE'),
  card('ai-zero-day', 'ai', 'Zero-Day Window', 'You patch the opening before anyone else notices it.', 'Digital opponents lose 1 AI Skill; Digital careers gain 2 AI Skill.', 'digital rivals -1 AI / digital +2 AI', [stat('aiSkill', -1, 'ALL_OPPONENTS', 'digital'), stat('aiSkill', 2, 'SELF', 'digital')], 'A neon vulnerability aperture closes around a lone security specialist and a cracked red firewall.'),

  // FAME
  card('fame-clip', 'fame', 'The Clip', 'One moment travels farther than you expected.', 'Gain 4 Fame.', '+4 FAME', [stat('fame', 4)], 'A phone screen captures one absurdly perfect moment as the clip spreads through a dark crowd.'),
  card('fame-cover', 'fame', 'Cover Story', 'Your name is suddenly impossible to ignore.', 'Gain 9 Fame.', '+9 FAME', [stat('fame', 9)], 'A premium magazine cover glows on a rainy kiosk while cameras crowd the midnight street.', 'RARE'),
  card('fame-sponsor-surge', 'fame', 'Sponsor Surge', 'A brand wants your face on the product before you understand it.', 'Gain 3 Fame and $10,000 Wealth.', '+3 FAME / +$10,000', [stat('fame', 3), stat('wealth', 10000)], 'A giant holographic sneaker launches through a cloud of paparazzi flashes and sponsorship confetti.'),
  card('fame-ragebait', 'fame', 'Ragebait Season', 'The engagement graph rises. The room gets colder.', 'Gain 5 Fame and lose 2 Influence.', '+5 FAME / -2 INFL.', [stat('fame', 5), stat('influence', -2)], 'A content creator stands before a towering red engagement graph as a comment storm swirls around them.'),
  card('fame-apology-tour', 'fame', 'Apology Tour', 'The first statement was rough. The second one had a lawyer.', 'Gain 2 Fame and 2 Influence.', '+2 FAME / +2 INFL.', [stat('fame', 2), stat('influence', 2)], 'A creator reads a careful apology from a small stage while a PR team signals from the wings.'),
  card('fame-scandal-leak', 'fame', 'Scandal Leak', 'The private group chat had a very public backup.', 'Lose 4 Fame and $8,000 Wealth.', '-4 FAME / -$8,000', [stat('fame', -4), stat('wealth', -8000)], 'A cracked phone spills redacted messages onto an enormous breaking-news wall.', 'RARE'),
  card('fame-fan-cam', 'fame', 'Fan-Cam Ambush', 'The crowd chooses a new favorite for the next thirty seconds.', 'A random opponent loses 2 Fame; you gain 1 Fame.', 'rival -2 FAME / +1 FAME', [stat('fame', -2, 'RANDOM_OPPONENT'), stat('fame', 1)], 'A stadium fan-cam swings from a stunned rival to a smiling player beneath a spotlight.'),
  card('fame-brand-deal', 'fame', 'Brand Deal Clause', 'The fee is real. The product is technically a beverage.', 'Gain $14,000 Wealth; Media careers gain 2 Fame.', '+$14,000 / media +2 FAME', [stat('wealth', 14000), stat('fame', 2, 'SELF', 'media')], 'A glossy contract wraps around an impossible neon drink can on a black studio set.', 'RARE'),
  card('fame-shadowban', 'fame', 'Shadowban', 'Your posts are still there. The audience is not.', 'Lose 3 Fame and gain 1 Lifestyle.', '-3 FAME / +1 LIFE', [stat('fame', -3), stat('lifestyle', 1)], 'A lone influencer stands in a dark empty room while their bright social feed fades to zero.'),
  card('fame-paparazzi-pack', 'fame', 'Paparazzi Pack', 'Someone else gets the flashbulbs for a change.', 'The Wealth leader loses 3 Fame; you gain 2 Fame.', 'leader -3 FAME / +2 FAME', [stat('fame', -3, 'WEALTH_LEADER'), stat('fame', 2)], 'A swarm of camera drones abandons a luxury car to chase a rival crossing the street.'),
  card('fame-charity-livestream', 'fame', 'Charity Livestream', 'The fundraiser is sincere. The camera angle is excellent.', 'Gain 3 Fame, 2 Influence, and $5,000 Wealth.', '+3 FAME / +2 INFL. / +$5,000', [stat('fame', 3), stat('influence', 2), stat('wealth', 5000)], 'A livestream host directs a glowing donation flood toward a neighborhood relief hub.'),
  card('fame-press-cycle', 'fame', 'Press Cycle', 'A whole news cycle is just your face and a weather map.', 'Gain 4 Fame; Media opponents lose 1 Fame.', '+4 FAME / media rivals -1', [stat('fame', 4), stat('fame', -1, 'ALL_OPPONENTS', 'media')], 'A split broadcast wall gives one figure the main headline while rival media screens dim.'),
  card('fame-cancel-proof', 'fame', 'Context Thread', 'A long thread, a timestamp, and one very useful receipt.', 'Gain 2 Fame and block the next Fame penalty.', '+2 FAME / block 1 Fame penalty', [stat('fame', 2), protect(1, ['REMOVE_FAME'])], 'A forensic timeline of receipts unfurls like a luminous shield in front of a public figure.'),
  card('fame-endorsement-clause', 'fame', 'Endorsement Clause', 'The spotlight brings a check and a strict no-comment section.', 'Gain $18,000 Wealth and lose 1 Influence.', '+$18,000 / -1 INFL.', [stat('wealth', 18000), stat('influence', -1)], 'A celebrity silhouette signs a contract beneath a wall of cameras and one ominous blank clause.', 'RARE'),
  card('fame-copycat-controversy', 'fame', 'Copycat Controversy', 'The imitation trends. The original gets the credit.', 'Gain 3 Fame; a random opponent loses 2 Fame.', '+3 FAME / rival -2', [stat('fame', 3), stat('fame', -2, 'RANDOM_OPPONENT')], 'Two near-identical masked performers face a trending-symbol storm, one sharply in focus.'),

  // LIFESTYLE
  card('lifestyle-detour', 'lifestyle', 'Take The Long Way', 'An unplanned stop becomes the whole story.', 'Gain 3 Lifestyle.', '+3 LIFE', [stat('lifestyle', 3)], 'A winding night road leaves the city behind and opens toward a quiet neon-lit coastline.'),
  card('lifestyle-reset', 'lifestyle', 'Full Reset', 'Clear the calendar. Make space for more.', 'Gain 7 Lifestyle.', '+7 LIFE', [stat('lifestyle', 7)], 'A person steps out of a crowded calendar projection into a serene minimalist room.', 'RARE'),
  card('lifestyle-spa-day', 'lifestyle', 'Machine-Assisted Spa Day', 'The wellness pod promises serenity and a firmware update.', 'Gain 2 Lifestyle and 1 AI Skill.', '+2 LIFE / +1 AI', [stat('lifestyle', 2), stat('aiSkill', 1)], 'A chrome spa pod releases a calm guest into a pool of blue light and soft vapor.'),
  card('lifestyle-yacht-day', 'lifestyle', 'Yacht Deposit', 'The ocean is free. The docking reservation is not.', 'Lose $15,000 Wealth and gain 5 Lifestyle.', '-$15,000 / +5 LIFE', [stat('wealth', -15000), stat('lifestyle', 5)], 'A small extravagant yacht cuts through a dark harbor beneath a vivid magenta sunset.', 'RARE'),
  card('lifestyle-sleep-debt', 'lifestyle', 'Sleep Debt', 'One more late night buys a little cash and a worse morning.', 'Gain $8,000 Wealth and lose 2 Lifestyle.', '+$8,000 / -2 LIFE', [stat('wealth', 8000), stat('lifestyle', -2)], 'A tired freelancer watches a sunrise from a desk crowded with cold coffee and invoices.'),
  card('lifestyle-biohack', 'lifestyle', 'Biohack Weekend', 'The tiny wearable tracks every metric except restraint.', 'Gain 3 Lifestyle; Performance careers gain 1 more.', '+3 LIFE / performance +1', [stat('lifestyle', 3), stat('lifestyle', 1, 'SELF', 'performance')], 'A runner calibrates a luminous wearable while a biometrics halo tracks a midnight sprint.'),
  card('lifestyle-digital-detox', 'lifestyle', 'Digital Detox', 'The phone goes in a box. The box is also smart.', 'Gain 2 Lifestyle and lose 1 AI Skill.', '+2 LIFE / -1 AI', [stat('lifestyle', 2), stat('aiSkill', -1)], 'A smartphone rests sealed in a transparent lockbox beside a sunlit analog journal.'),
  card('lifestyle-vacation-rebook', 'lifestyle', 'Vacation Rebook', 'The flight changes twice. The refund arrives once.', 'Gain $5,000 Wealth and lose 1 Lifestyle.', '+$5,000 / -1 LIFE', [stat('wealth', 5000), stat('lifestyle', -1)], 'A holographic departure board flips destinations while a traveler clutches a half-refunded ticket.'),
  card('lifestyle-collector-pivot', 'lifestyle', 'Collector Pivot', 'The rare object is sold to buy a rarer experience.', 'Gain 3 Lifestyle and 2 Fame; lose $11,000 Wealth.', '+3 LIFE / +2 FAME / -$11,000', [stat('lifestyle', 3), stat('fame', 2), stat('wealth', -11000)], 'A collectible neon helmet leaves a glass case as its owner books a surreal desert retreat.'),
  card('lifestyle-sabbatical', 'lifestyle', 'Unpaid Sabbatical', 'You step away from the grind and pay for the privilege.', 'Gain 4 Lifestyle and lose $10,000 Wealth.', '+4 LIFE / -$10,000', [stat('lifestyle', 4), stat('wealth', -10000)], 'A professional closes a laptop beside a quiet mountain cabin under a huge dusk sky.', 'RARE'),
  card('lifestyle-pet-spa', 'lifestyle', 'Pet Spa Upgrade', 'Your companion gets better service than your last hotel.', 'Gain 3 Lifestyle and 1 Fame.', '+3 LIFE / +1 FAME', [stat('lifestyle', 3), stat('fame', 1)], 'A tiny dog in a silver robe lounges in a futuristic spa as its owner films the moment.'),
  card('lifestyle-home-gym', 'lifestyle', 'Home Gym Spiral', 'The equipment is delivered. The subscription is forever.', 'Lose $8,000 Wealth and gain 4 Lifestyle; Performance careers gain 1 more.', '-$8,000 / +4 LIFE', [stat('wealth', -8000), stat('lifestyle', 4), stat('lifestyle', 1, 'SELF', 'performance')], 'A compact apartment fills with polished gym machinery as a trainer adjusts a bright resistance rig.', 'RARE'),
  card('lifestyle-wellness-scam', 'lifestyle', 'Wellness Subscription', 'The trial was free. The cancellation button is folklore.', 'Lose $6,000 Wealth and 1 Lifestyle.', '-$6,000 / -1 LIFE', [stat('wealth', -6000), stat('lifestyle', -1)], 'A smiling wellness app mascot hides a chain of subscription charges behind a glowing phone.'),
  card('lifestyle-midnight-upgrade', 'lifestyle', 'Midnight Upgrade', 'The new chair is ergonomic enough to justify the delivery fee.', 'Lose $4,000 Wealth and gain 2 Lifestyle.', '-$4,000 / +2 LIFE', [stat('wealth', -4000), stat('lifestyle', 2)], 'A sculptural gaming chair arrives under a spotlight in a tiny midnight studio.'),
  card('lifestyle-quiet-weekend', 'lifestyle', 'Quiet Weekend', 'No plans, no notifications, and one very expensive candle.', 'Gain 2 Lifestyle and block the next negative Lifestyle effect.', '+2 LIFE / block 1 LIFE penalty', [stat('lifestyle', 2), protect(1, ['REMOVE_LIFESTYLE'])], 'A single candle glows in a silent loft while a phone’s notifications dissolve into the dark.'),

  // INFLUENCE
  card('influence-intro', 'influence', 'Warm Introduction', 'Someone opens a door before you knock.', 'Gain 3 Influence.', '+3 INFL.', [stat('influence', 3)], 'A discreet host opens a gold-lit doorway between two people at a crowded private event.'),
  card('influence-room', 'influence', 'In The Room', 'The conversation changes when you arrive.', 'Gain 8 Influence.', '+8 INFL.', [stat('influence', 8)], 'A confident figure enters a boardroom as every chair turns toward the open door.', 'RARE'),
  card('influence-backchannel', 'influence', 'Backchannel', 'A quiet message moves faster than the official agenda.', 'Gain 2 Influence and take $5,000 from the Wealth leader.', '+2 INFL. / up to +$5,000', [stat('influence', 2), transfer(5000, 'WEALTH_LEADER')], 'Two phones exchange a coded message beneath a glass table while a gold coin changes hands.'),
  card('influence-board-seat', 'influence', 'Board Seat', 'You are invited to advise. The vote is already scheduled.', 'Gain 3 Influence; Business careers gain $8,000 Wealth.', '+3 INFL. / business +$8,000', [stat('influence', 3), stat('wealth', 8000, 'SELF', 'business')], 'A single illuminated chair waits at the center of a vast black corporate boardroom.', 'RARE'),
  card('influence-favor-bank', 'influence', 'Favor Bank', 'You call in one favor and leave the ledger slightly worse for everyone.', 'Gain 4 Influence; opponents lose 1 Influence.', '+4 INFL. / rivals -1', [stat('influence', 4), stat('influence', -1, 'ALL_OPPONENTS')], 'A towering ledger opens as small favors flow toward one figure and away from three rivals.'),
  card('influence-union-card', 'influence', 'Union Card', 'A whole network agrees that this penalty can wait.', 'Gain 1 Influence and block the next Wealth penalty.', '+1 INFL. / block 1 Wealth penalty', [stat('influence', 1), protect(1, ['REMOVE_WEALTH'])], 'A worker holds up a silver membership card as a ring of colleagues closes ranks.'),
  card('influence-favor-called-in', 'influence', 'Favor Called In', 'The favor returns in cash, not gratitude.', 'Take up to $9,000 from a random opponent.', 'up to +$9,000', [transfer(9000, 'RANDOM_OPPONENT')], 'A discreet envelope passes across a restaurant table while a surprised rival checks an empty wallet.'),
  card('influence-warm-handoff', 'influence', 'Warm Handoff', 'You connect two people who both remember who made the introduction.', 'Gain 2 Influence; a random opponent gains 1 Fame.', '+2 INFL. / rival +1 FAME', [stat('influence', 2), stat('fame', 1, 'RANDOM_OPPONENT')], 'Two strangers shake hands under a spotlight as the connector steps back into the shadows.'),
  card('influence-veto-vote', 'influence', 'Veto Vote', 'The proposal dies in committee. The room remembers who stopped it.', 'Business opponents lose 2 Influence; you gain 2 Influence.', 'business rivals -2 / +2 INFL.', [stat('influence', -2, 'ALL_OPPONENTS', 'business'), stat('influence', 2)], 'A red veto stamp slams across a glowing corporate proposal while executives recoil.'),
  card('influence-shield-network', 'influence', 'Shield Network', 'Three people make one phone call each. The problem disappears.', 'Gain 2 Influence and block the next 2 negative effects.', '+2 INFL. / block 2 penalties', [stat('influence', 2), protect(2)], 'A web of luminous contacts closes into a protective shield around a calm central figure.', 'RARE'),
  card('influence-corporate-lobby', 'influence', 'Lobbyist’s Lunch', 'The menu is expensive. The policy change is more expensive.', 'Gain $12,000 Wealth and lose 1 Fame.', '+$12,000 / -1 FAME', [stat('wealth', 12000), stat('fame', -1)], 'A private dining room overlooks a government building as a polished folder slides across the table.'),
  card('influence-public-endorsement', 'influence', 'Public Endorsement', 'Your support helps a rival, and makes your own name travel farther.', 'Gain 3 Influence; all opponents gain 1 Fame.', '+3 INFL. / rivals +1 FAME', [stat('influence', 3), stat('fame', 1, 'ALL_OPPONENTS')], 'A speaker raises a rival’s hand at a crowded rally as cameras capture the endorsement.'),
  card('influence-donor-list', 'influence', 'Donor List', 'The names are familiar. The total is not small.', 'Gain $10,000 Wealth and 2 Influence.', '+$10,000 / +2 INFL.', [stat('wealth', 10000), stat('influence', 2)], 'An elegant black invitation reveals a luminous donor list and a growing stack of checks.', 'RARE'),
  card('influence-fixer', 'influence', 'The Fixer', 'The complication is handled before it becomes a headline.', 'Gain 2 Influence and block the next Fame penalty.', '+2 INFL. / block 1 Fame penalty', [stat('influence', 2), protect(1, ['REMOVE_FAME'])], 'A composed fixer closes a briefcase as a wall of reporters loses its story.'),
  card('influence-ghosted', 'influence', 'Ghosted by the Network', 'A door quietly closes for the person who thought it was guaranteed.', 'The Wealth trailer loses 3 Influence; you gain 2 Influence.', 'trailer -3 / +2 INFL.', [stat('influence', -3, 'WEALTH_TRAILER'), stat('influence', 2)], 'A glowing contact map drops one isolated figure from its network while another gains a bright connection.'),

  // GAMBLE
  card('gamble-call', 'gamble', 'Double Or Nothing', 'The next move asks for nerve, not certainty.', '50%: gain $37,000 Wealth. Otherwise lose $18,500.', '+$37,000 or -$18,500', [risk(0.5, [stat('wealth', 37000)], [stat('wealth', -18500)])], 'A roulette wheel spins between a towering pile of gold and a red-lit empty table.', 'RARE'),
  card('gamble-edge', 'gamble', 'Against The Odds', 'A narrow opening and a very loud clock.', '35%: gain $36,750 Wealth. Otherwise lose $12,250.', '+$36,750 or -$12,250', [risk(0.35, [stat('wealth', 36750)], [stat('wealth', -12250)])], 'A lone gambler reaches toward a thin glowing bridge above a deep red casino void.', 'RARE'),
  card('gamble-coin-flip', 'gamble', 'Coin-Flip Fame', 'The stunt either lands perfectly or lives forever for the wrong reason.', '50%: gain 4 Fame. Otherwise lose 3 Fame.', '+4 or -3 FAME', [risk(0.5, [stat('fame', 4)], [stat('fame', -3)])], 'A spinning coin hangs between a cheering crowd and a wall of laughing reaction screens.'),
  card('gamble-prediction-market', 'gamble', 'Prediction Market', 'You put a number on the future and the future notices.', '60%: gain $20,000 Wealth. Otherwise lose $10,000; Digital careers gain 1 AI Skill.', '+$20,000 or -$10,000', [risk(0.6, [stat('wealth', 20000)], [stat('wealth', -10000), stat('aiSkill', 1, 'SELF', 'digital')])], 'A holographic futures market charts a green upward arc above a crowded prediction terminal.', 'RARE'),
  card('gamble-hot-hand', 'gamble', 'Hot Hand', 'Confidence is useful right up until the chart turns around.', '55%: gain 4 AI Skill and 1 Fame. Otherwise lose 2 AI Skill.', '+4 AI / +1 FAME or -2 AI', [risk(0.55, [stat('aiSkill', 4), stat('fame', 1)], [stat('aiSkill', -2)])], 'A gamer’s glowing hands move in a blur as an unstable streak of symbols changes color.'),
  card('gamble-short-squeeze', 'gamble', 'Short Squeeze', 'The Wealth leader blinks first. You are already holding the exit.', '50%: take $10,000 from the leader. Otherwise lose $12,000.', 'up to +$10,000 or -$12,000', [risk(0.5, [transfer(10000, 'WEALTH_LEADER')], [stat('wealth', -12000)])], 'A red market chart snaps upward, trapping a luxury investor against a wall of rising numbers.', 'RARE'),
  card('gamble-stat-conversion', 'gamble', 'Lifestyle Arbitrage', 'You trade comfort for momentum and hope the math is kind.', '50%: gain 4 Lifestyle. Otherwise lose 2 Lifestyle and 1 Influence.', '+4 LIFE or -2 LIFE / -1 INFL.', [risk(0.5, [stat('lifestyle', 4)], [stat('lifestyle', -2), stat('influence', -1)])], 'A glossy lounge chair balances precariously against a stack of influence tokens on a red seesaw.'),
  card('gamble-triple-or-bust', 'gamble', 'Triple Or Bust', 'The payout is loud. The probability is not.', '33%: gain $30,000 Wealth. Otherwise lose $10,000.', '+$30,000 or -$10,000', [risk(0.33, [stat('wealth', 30000)], [stat('wealth', -10000)])], 'Three gold tokens orbit a single red chip above a dark casino felt table.', 'RARE'),
  card('gamble-redline-rush', 'gamble', 'Redline Rush', 'You push the model past the warning it politely displayed.', '60%: gain 5 AI Skill. Otherwise lose 4 AI Skill and $8,000.', '+5 AI or -4 AI / -$8,000', [risk(0.6, [stat('aiSkill', 5)], [stat('aiSkill', -4), stat('wealth', -8000)])], 'A neural engine overheats along a vivid red track as an operator reaches for the cutoff switch.'),
  card('gamble-favor-roulette', 'gamble', 'Favor Roulette', 'Someone answers the call. The question is who owes whom afterward.', '50%: take $8,000 from a random opponent. Otherwise lose 3 Influence.', 'up to +$8,000 or -3 INFL.', [risk(0.5, [transfer(8000, 'RANDOM_OPPONENT')], [stat('influence', -3)])], 'A spinning contact wheel lands between a sealed envelope and a broken phone connection.'),
  card('gamble-mood-swing', 'gamble', 'Influence Swing', 'One risky endorsement could move the whole room.', '45%: gain 6 Influence. Otherwise lose 4 Influence.', '+6 or -4 INFL.', [risk(0.45, [stat('influence', 6)], [stat('influence', -4)])], 'A crowd pivots as one, pulling a lone speaker toward a bright stage or a dark exit.', 'RARE'),
  card('gamble-market-blackout', 'gamble', 'Market Blackout', 'The circuit goes dark. Someone still has to pay the clearing price.', '50%: gain $24,000 Wealth. Otherwise lose $8,000 while opponents gain $2,000 each.', '+$24,000 or -$8,000 / rivals +$2,000', [risk(0.5, [stat('wealth', 24000)], [stat('wealth', -8000), stat('wealth', 2000, 'ALL_OPPONENTS')])], 'A citywide trading grid blacks out except for one glowing exchange floor and scattered red screens.'),
  card('gamble-double-exposure', 'gamble', 'Double Exposure', 'Two cameras, one bet, and no control over the clip.', '40%: gain $15,000 Wealth and 3 Fame. Otherwise lose $15,000 and 2 Fame.', '+$15,000 / +3 FAME or losses', [risk(0.4, [stat('wealth', 15000), stat('fame', 3)], [stat('wealth', -15000), stat('fame', -2)])], 'A gambler stands between a gold spotlight and a pair of cameras recording opposite outcomes.'),
  card('gamble-last-chip', 'gamble', 'Last Chip', 'The final chip gets one more chance to be a terrible idea.', '25%: gain $32,000 Wealth. Otherwise lose $16,000.', '+$32,000 or -$16,000', [risk(0.25, [stat('wealth', 32000)], [stat('wealth', -16000)])], 'A solitary red chip rolls across a vast black table toward a distant gold payout slot.', 'RARE'),
  card('gamble-wild-reversal', 'gamble', 'Wild Reversal', 'The table turns over. Your opponent may be underneath it.', '50%: take 3 Influence from a random opponent. Otherwise lose 2 Influence.', 'rival -3 / +3 INFL. or -2 INFL.', [risk(0.5, [stat('influence', -3, 'RANDOM_OPPONENT'), stat('influence', 3)], [stat('influence', -2)])], 'A roulette table flips into a chaotic storm of red chips and scattered influence tokens.'),
];

export const cardsForDeck = (deck: DeckId): readonly CardDefinition[] => cards.filter(card => card.deck === deck);
export const examplesForDeck = cardsForDeck;
export const getCard = (cardId: string): CardDefinition | undefined => cards.find(card => card.id === cardId);