export const CARD_READ_MINIMUM_MS = 2_200;
export const CPU_CARD_RESULT_MS = 2_400;
export const CPU_CARD_AUTO_CONTINUE_MS = CARD_READ_MINIMUM_MS + CPU_CARD_RESULT_MS;

export const CARD_READ_MINIMUM_SECONDS = (CARD_READ_MINIMUM_MS / 1_000).toFixed(1);
export const CPU_CARD_RESULT_SECONDS = (CPU_CARD_RESULT_MS / 1_000).toFixed(1);