// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/redline-pawns/Current.tsx": () => import("../components/mockups/redline-pawns/Current.tsx"),
  "./components/mockups/redline-pawns/Gallery.tsx": () => import("../components/mockups/redline-pawns/Gallery.tsx"),
  "./components/mockups/redline-pawns/Sculpted.tsx": () => import("../components/mockups/redline-pawns/Sculpted.tsx")
};
